using System;
using Gwen.Net.Skin;

namespace Gwen.Net.Control
{
    /// <summary>
    ///     Progress bar.
    /// </summary>
    public class ProgressBar : Label
    {
        private Single progress;

        /// <summary>
        ///     Initializes a new instance of the <see cref="ProgressBar" /> class.
        /// </summary>
        /// <param name="parent">Parent control.</param>
        public ProgressBar(ControlBase parent)
            : base(parent)
        {
            SetSize(width: 128, height: 32);
            TextPadding = Padding.Three;
            IsHorizontal = true;

            AutoSizeToContents = false;
            Alignment = Alignment.Center;
            progress = 0;
            AutoLabel = true;
        }

        /// <summary>
        ///     Determines whether the control is horizontal.
        /// </summary>
        public Boolean IsHorizontal { get; set; }

        /// <summary>
        ///     Progress value (0-1).
        /// </summary>
        public Single Value
        {
            get => progress;
            set
            {
                if (value < 0)
                {
                    value = 0;
                }

                if (value > 1)
                {
                    value = 1;
                }

                progress = value;

                if (AutoLabel)
                {
                    var displayVal = (Int32) (progress * 100);
                    Text = displayVal + "%";
                }
            }
        }

        /// <summary>
        ///     Determines whether the label text is autogenerated from value.
        /// </summary>
        public Boolean AutoLabel { get; set; }

        /// <summary>
        ///     Renders the control using specified skin.
        /// </summary>
        /// <param name="currentSkin">Skin to use.</param>
        protected override void Render(SkinBase currentSkin)
        {
            currentSkin.DrawProgressBar(this, IsHorizontal, progress);
        }
    }
}
