using Gwen.Net.Skin;
using Gwen.Net.Xml;

namespace Gwen.Net.Control
{
    /// <summary>
    ///     Progress bar.
    /// </summary>
    [XmlControl]
    public class ProgressBar : Label
    {
        private float m_Progress;

        /// <summary>
        ///     Initializes a new instance of the <see cref="ProgressBar" /> class.
        /// </summary>
        /// <param name="parent">Parent control.</param>
        public ProgressBar(ControlBase parent)
            : base(parent)
        {
            SetSize(width: 128, height: 32);
            TextPadding = Padding.Three;
            IsHorizontal = true;

            AutoSizeToContents = false;
            Alignment = Alignment.Center;
            m_Progress = 0;
            AutoLabel = true;
        }

        /// <summary>
        ///     Determines whether the control is horizontal.
        /// </summary>
        [XmlProperty] public bool IsHorizontal { get; set; }

        /// <summary>
        ///     Progress value (0-1).
        /// </summary>
        [XmlProperty] public float Value
        {
            get => m_Progress;
            set
            {
                if (value < 0)
                {
                    value = 0;
                }

                if (value > 1)
                {
                    value = 1;
                }

                m_Progress = value;

                if (AutoLabel)
                {
                    var displayVal = (int) (m_Progress * 100);
                    Text = displayVal + "%";
                }
            }
        }

        /// <summary>
        ///     Determines whether the label text is autogenerated from value.
        /// </summary>
        [XmlProperty] public bool AutoLabel { get; set; }

        /// <summary>
        ///     Renders the control using specified skin.
        /// </summary>
        /// <param name="skin">Skin to use.</param>
        protected override void Render(SkinBase skin)
        {
            skin.DrawProgressBar(this, IsHorizontal, m_Progress);
        }
    }
}
